#!/bin/sh
#
# Copyright (c) 2023 LENAR
#

# RN=$(( (RANDOM % 51) * 5 + 5 ))

uci -q batch <<-EOF >/dev/null
  # Set system properties
  set system.@system[0].hostname="HKM281"
  set system.@system[0].conloglevel="7"
  set system.@system[0].cronloglevel="8"

  # Configure NTP servers
  del system.ntp.server
  add_list system.ntp.server="asia.pool.ntp.org"
  add_list system.ntp.server="0.id.pool.ntp.org"
  add_list system.ntp.server="1.id.pool.ntp.org"

  # Luci language
  set luci.main.lang="auto"

  # Change LAN IP Address
  # set network.lan.ipaddr="192.168.${RN}.1"

# Mengatur nama zona waktu
  set system.@system[0].zonename="Asia/Jakarta"

# Mengatur kode string zona waktu (WIB-7)
  set system.@system[0].timezone="WIB-7"

  # Apply changes
  commit system
  commit ntp
  commit luci
  # commit network
EOF

exit 0
